version: "3.9"

services:
  db:
    image: postgres:16
    container_name: resumematcher_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resumematcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: resumematcher_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/resumematcher
      JWT_SECRET: supersecretkey
      JWT_ALGO: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"

volumes:
  postgres_data:
